name: "api-gateway"
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/api-gateway
  tag: "latest"
  
service:

volume:
  mountPath: /dist/
  secretName: azure-secret
  shareName: momentum/utils


configmap:
  configmaps:  
  mame: momentum-configmap
