name: 'api-gateway'
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/api-gateway
  tag: "latest"

service:
  ports:
  - name: http
    port: "8080"

volume:
  mountPath: /usr/src/app/src/utils
  secretName: azure-secret
  shareName: momentum/spike-utils

config:
  configmaps:
  mame: momentum-configmap

ingress:
  enabled: true
  hosts:
  - host: momentum.branch-yesodot.org
    paths:
      - path: /api
        service: api-gateway
        port: 8080
