name: "api-gateway"
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/api-gateway
  tag: "latest"

service:
  ports:
  - name: http
    port: "8080"

volume:
  - name: api-gate-spike-utils
    mountPath: /spikeUtils
    secretName: azure-secret
    shareName: momentum/spike-utils
    type: azurefile
  
  - name: bulk-files-utils
    mountPath: /bulkFiles
    secretName: azure-secret
    shareName: momentum/bulk-files
    type: azurefile
  
  - name: logs
    mountPath: /logs
    secretName: azure-secret
    shareName: momentum/logs
    type: azurefile

config:
  configmaps:
      name: momentum-configmap


ingress:
  enabled: true
  hosts:
  - host: momentum.branch-yesodot.org
    paths:
      - path: /api
        service: api-gateway
        port: 8080

# livenessProbe:
#       httpGet:
#         path: /api/isAlive
#         port: 8080
#       initialDelaySeconds: 5
#       periodSeconds: 5
#       timeoutSeconds: 1
#       successThreshold: 1
#       failureThreshold: 3
# readinessProbe:
#   httpGet:
#     path: /api/isAlive
#     port: 8080
#   initialDelaySeconds: 5
#   periodSeconds: 5
#   timeoutSeconds: 1
#   successThreshold: 1
#   failureThreshold: 3
