name: "api-gateway"
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/api-gateway
  tag: "latest"

service:
  ports:
  - name: http
    port: "8080"

volume:
  - name: bulk-files-utils
    type: azurefile
    secretName: azure-secret
    shareName: momentum/bulk-files
    mounts:
      - mountPath: /bulkFiles

  - name: logs
    type: azurefile
    secretName: azure-secret
    shareName: momentum/logs
    mounts:
      - mountPath: /logs

  - name: api-gate-spike-utils
    type: azurefile
    secretName: azure-secret
    shareName: momentum/spike-utils
    mounts:
      - mountPath: /spikeUtils

config:
  configmaps:
      name: momentum-configmap


ingress:
  enabled: true
  hosts:
  - host: momentum.branch-yesodot.org
    paths:
      - path: /api
        service: api-gateway
        port: 8080
