name: 'api-gateway'
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/api-gateway
  tag: 'latest'

service:

volume:
  mountPath: /usr/src/app/src/utils
  secretName: azure-secret
  shareName: momentum/spike-utils

configmap:
  configmaps:
  mame: momentum-configmap
