name: "kartoffel-consumer"
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/kartoffel-consumer
  tag: "latest"
service:
configmap:
  configmaps:  
  mame: momentum-configmap
