version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass "mozart"
    volumes:
      - ./data/data:/data
    ports:
      - 6379:6379
    restart: unless-stopped

  spike-service:
    image: spike-service
    build: ./spike-service/
    env_file:
      - ./supernova.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SS_REDIS_HOST=redis
      - SS_REDIS_PORT=6379
      - SS_REDIS_PASSWORD=mozart

  request-service:
    image: request-service
    build: ./request-service/
    env_file:
      - ./supernova.env
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    environment:
      - RS_MONGO_URL=mongodb://mongodb:27017/supernova

  kartoffel-service:
    image: kartoffel-service
    build: ./kartoffel-service/
    env_file:
      - ./supernova.env
    ports:
      - "8082:8080"
    depends_on:
      - spike-service
    environment:
      - KS_USE_FAKER=true

  producer-service:
    image: producer-service
    build: ./producer-service/
    env_file:
      - ./supernova.env
    ports:
      - "8083:8080"
    depends_on:
      - kartoffel-service
