name: 'tea-service'
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/tea-service
  tag: 'latest'
service:
  ports:
    - name: http-ts
      port: '8080'
config:
  configmaps:
    name: momentum-configmap

volume:
  - name: tea-utils
    mountPath: /teaUtils
    secretName: azure-secret
    shareName: momentum/tea-utils
    type: azurefile

livenessProbe:
  exec:
    command: ["/bin/grpc_health_probe", "-addr=:8080"]
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  exec:
    command: ["/bin/grpc_health_probe", "-addr=:8080"]
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3