name: "whitelistsync-script"
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/whitelistsync-script
  tag: "latest"
service:
configmap:
  configmaps:  
    name: momentum-configmap
