export enum RequestType {
  CREATE_OG = "CREATE_OG",
  CREATE_ROLE = "CREATE_ROLE",
  ASSIGN_ROLE_TO_ENTITY = "ASSIGN_ROLE_TO_ENTITY",
  CREATE_ENTITY = "CREATE_ENTITY",
  RENAME_OG = "RENAME_OG",
  RENAME_ROLE = "RENAME_ROLE",
  EDIT_ENTITY = "EDIT_ENTITY",
  DELETE_OG = "DELETE_OG",
  DELETE_ROLE = "DELETE_ROLE",
  DISCONNECT_ROLE = "DISCONNECT_ROLE",
}
