export enum PersonTypeInRequest {
  COMMANDER = 'COMMANDER',
  SUBMITTER = 'SUBMITTER',
  SECURITY_APPROVER = 'SECURITY_APPROVER',
  SUPER_SECURITY_APPROVER = 'SUPER_SECURITY_APPROVER',
  APPROVER = 'APPROVER',
}
