name: "authentication-service"
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/authentication-service
  tag: "latest"
service:
  ports:
  - name: http
    port: "3000"
configmap:
  configmaps:  
    name: momentum-configmap

ingress:
  enabled: true
  hosts:
  - host: momentum.branch-yesodot.org
    paths:
      - path: /auth
        service: authentication-service
        port: 3000