name: "mail-service"
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/mail-service
  tag: "latest"

service:
  ports:
  - name: http
    port: "8080"
    
config:
  configmaps:
      name: momentum-configmap

