name: "bulk-service"
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/bulk-service
  tag: "latest"
  
service:
  ports:
  - name: http
    port: "3000"

volume:
  mountPath: /usr/src/app/bulk-files
  secretName: azure-secret
  shareName: momentum/bulk-files

config:
  configmaps:
      name: momentum-configmap
