name: 'spike-service'
# If you want to overide the full name you can include the 'fullnameOverride' value
#fullname:
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: momentumacr.azurecr.io/spike-service
  tag: 'latest'
service:
configmap:
  configmaps:
  mame: momentum-configmap

volume:
  mountPath: /usr/src/app/spike-utils
  secretName: azure-secret
  shareName: momentum/spike-utils
